### ISSUE TITLE
Is the CT dataset SPREAD available for downloading?

### ISSUE THREAD

**Issue by lxmwust** [hsokooti/RegNet#1]
The code is great. Is the used CT dataset SPREAD for experiments publicly available?

**Comment by hsokooti** [comment]
Thank you for your interest in our work. 

Unfortunately, the [SPREAD ](http://www.resmedjournal.com/article/S0954-6111(07)00186-2/abstract)database will remain closed because it is going to be used as a blinded-experiment in the [WBIR2018](https://wbir2018.nl/) registration challenge.

**Comment by lxmwust** [comment]
Thank you for the reply. 
I am new to the image registration problem. Since the SPREAD dataset is not available, it would be great if you can provide a basic demo with an open accessible dataset.

**Comment by hsokooti** [comment]
I would suggest other open accessible chest CT databases like [DIR-Lab](https://www.dir-lab.com/index.html) and  [Popi](https://www.creatis.insa-lyon.fr/rio/popi-model_original_page). Similar to the [SPREAD](http://www.resmedjournal.com/article/S0954-6111(07)00186-2/abstract) database, several distinctive landmarks are annotated. I would expect that the RegNet performs the same way as in the SPREAD dataset.

**Comment by lxmwust** [comment]
OK. Thank you for the suggestions and the great work.
