### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by zwep** [hsokooti/RegNet#2]
Dear Hsokooti,

thanks for creating this repo. I have read your paper and it looks interesting... hence I would like to replicate it myself. However I do notice that (IMO) your code can be improved. Both in terms of readability as well as reduction in redundancy. Since I want to help to improve it, I would like to offer my suggestions. However I don't know how to 'post' these.. are you able to help me with that?

Besides that I have, for now, one question that I want to ask. In the script where you create synthetic DVFs, there is a option for blob() and smooth(). Both create a DVFb, but blob(), in addition, creates an DeformedArea surface.
As far as I could tell, the DVFb is introduced to transform one set of images to a transformed version. This fixed and moved image are then used to train the model.
However, I cant find where the DeformedArea object is used again. I believe you do show an image of that in the README.md, but I don't see that it transform some original image like DVFb does. Am I missing something?

**Comment by hsokooti** [comment]
Dear zwep,

Thank you very much for your interest in our work. Indeed, you are right that this version of the code is not very readable. I've updated most parts of the code. I'll try to merge them here as soon as possible. Any suggestions about the code are really welcome and I would appreciate it. You might contact me by [email](https://www.lumc.nl/org/radiologie/medewerkers/1026263?setlanguage=English&setcountry=en).  

The difference between the function blob() and smooth() is that in blob() the Guassian blob have (almost) no overlap. At this version, the DeformedArea can only be used for debugging. Previously, it was used to force that all samples were chosen in this area to avoid having many zero displacement vector field in the training/validation phase. 

Hessam

**Comment by zwep** [comment]
Ah great, thanks!

If you want to look at the changes.. check my [https://github.com/zwep/MID/tree/master/models/RegNet](repo)

However, it contains some errors now due to my miss interpretation of blob and smooth () :)

**Comment by hsokooti** [comment]
Cool! I guess we can check and update the codes again when both repositories reach to the final state. 
Thank you very much for your feedback and contribution.

**Comment by zwep** [comment]
Short question... in SyntheticDeformation.py, you call

``DeformedDVF = sitk.GetImageFromArray(self._DeformedDVF_, isVector=True)``

Where self._DeformedDVF_ is a tensor/matrix of size 

``np.zeros([self._FixedIm_.shape[0], self._FixedIm_.shape[1], self._FixedIm_.shape[2], 3], dtype=np.float64)``

Thus this means that _DeformedDVF_ will have shape of something like (a x b x c x 3). If we then say to the Image from this (hence numpy array to itk array) with isVector=True, then we interpret the input as a 2D array.. But shouldnt it be seen as a 3D array with 3 slices? (for the DVF of the x, y and z direction)

**Comment by hsokooti** [comment]
If the input to the function ``sitk.GetImageFromArray(arr, isVector=True)`` is 3D, then the output is will be a vector consists of 2D images. However, if the input is 4D, the output will be a vector consists of 3D images.
Running the following code might clarify more:

```python
DVF_2D_sitk = sitk.GetImageFromArray(np.zeros([100, 101, 2]), isVector=True)
DVF_3D_sitk = sitk.GetImageFromArray(np.zeros([100, 101, 102, 3]), isVector=True)
print(DVF_2D_sitk)
print(DVF_3D_sitk)
```

```python
VectorImage (0000000003DF1CD0)
  RTTI typeinfo:   class itk::VectorImage<double,2>
  Reference Count: 1
  Modified Time: 773
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 0
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [101, 100]
  BufferedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [101, 100]
  RequestedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [101, 100]
  Spacing: [1, 1]
  Origin: [0, 0]
  Direction: 
1 0
0 1

  IndexToPointMatrix: 
1 0
0 1

  PointToIndexMatrix: 
1 0
0 1

  Inverse Direction: 
1 0
0 1

  VectorLength: 2
  PixelContainer: 
    ImportImageContainer (000000000453CD00)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,double>
      Reference Count: 1
      Modified Time: 774
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 000000000453D4F0
      Container manages memory: true
      Size: 20200
      Capacity: 20200

```
```python
VectorImage (0000000003143D60)
  RTTI typeinfo:   class itk::VectorImage<double,3>
  Reference Count: 1
  Modified Time: 779
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 0
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [102, 101, 100]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [102, 101, 100]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [102, 101, 100]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction: 
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix: 
1 0 0
0 1 0
0 0 1

  PointToIndexMatrix: 
1 0 0
0 1 0
0 0 1

  Inverse Direction: 
1 0 0
0 1 0
0 0 1

  VectorLength: 3
  PixelContainer: 
    ImportImageContainer (000000000453BD70)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,double>
      Reference Count: 1
      Modified Time: 780
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0000000005E70040
      Container manages memory: true
      Size: 3090600
      Capacity: 3090600

```
