### ISSUE TITLE
SimpleITK ReadImage error

### ISSUE THREAD

**Issue by nagdawi** [hsokooti/RegNet#4]
RuntimeError: Exception thrown in SimpleITK ReadImage: C:\Users\dashboard\Miniconda3\conda-bld\simpleitk_1521730316398\work\Code\IO\src\sitkImageReaderBase.cxx:89:
sitk::ERROR: The file "/srv/2-lkeb-16-reg1/hsokooti/DL/Elastix/LungExp/ExpLung11/Result/MovingImageFullRS1.mha" does not exist.

**Comment by hsokooti** [comment]
The data is not available in this repository. 

This software considers both fixed and moving images are available in the database. It reads images with the following addresses: 
```
Setting['DLFolder']/Elastix/LungExp/ExpLung1/Result/FixedImageFullRS1.mha
Setting['DLFolder']/Elastix/LungExp/ExpLung1/Result/MovingImageFullRS1.mha
Setting['DLFolder']/Elastix/LungExp/ExpLung2/Result/FixedImageFullRS1.mha
...
```
You can use open accessible chest CT databases like [DIR-Lab](https://www.dir-lab.com/index.html), [Popi](https://www.creatis.insa-lyon.fr/rio/popi-model_original_page) and [EMPIRE10](http://empire10.isi.uu.nl/).
