### ISSUE TITLE
where Can I download the dataset?

### ISSUE THREAD

**Issue by ahuczp** [hsokooti/RegNet#5]
Hi .I want to run your code.but how to get the dataset ?Thank you .

**Comment by hsokooti** [comment]
Hi, I would suggest other open accessible chest CT databases like [DIR-Lab](https://www.dir-lab.com/index.html), [Popi](https://www.creatis.insa-lyon.fr/rio/popi-model_original_page) and [EMPIRE10](http://empire10.isi.uu.nl/). Similar to the [SPREAD](http://www.resmedjournal.com/article/S0954-6111(07)00186-2/abstract) database, several distinctive landmarks are annotated. I would expect that the RegNet performs the same way as in the SPREAD dataset.

**Comment by Zumbalamambo** [comment]
@hsokooti is it for outlier detection?

**Comment by hsokooti** [comment]
@Zumbalamambo No!
