### ISSUE TITLE
patch concatenate

### ISSUE THREAD

**Issue by cs123951** [hsokooti/RegNet#9]
Hi, thank you for that your code have helped me a lot.
However, I am confused about some of your ideas, especially about patch. 

1. From the function “next_sweep_patch()” in functions.reading.real_pair, it seems that you get patches from image pair, and then concatenate these patches to form DVF. But this is easy to generate wrong correspondings between adjacent DVF. i.e. It's obvious that there are traces between patches in the final DVF. Like this:
![image](https://user-images.githubusercontent.com/13451757/64683762-798e0e00-d4b6-11e9-9170-f53d0719a2ca.png)

How to solve this problem? 

2.  The input size in Function.RegNetModel.decimation3 is (155,155,155) and the output size is (27,27,27,3). Then the output is the DVF for the center part (27,27,27) in (155,155,155)?

Thanks a lot if you could answer my doubts.

**Comment by hsokooti** [comment]
Hi Joy Lu,

Thank you for your interest in our project. 

1. About the stitching issue, is the attached DVF obtained from the decimation3 network?
Unfortunately,  I do not have any DVF samples from the decimation3 network in the meantime. However, I checked the results of [decimation4](https://github.com/hsokooti/RegNet/blob/master/functions/RegNetModel/decimation4.py) network and apparently there is no issue in the stitching process:
![Sample DVF_s](https://user-images.githubusercontent.com/12530760/64713496-4438ee80-d4bd-11e9-9fc7-ae48331eac7a.png)
The input size of this network is 105 and the output size is 21. It is possible to increase the input/output size with a multiple of 4 at the test time. 

2. Your point is completely true.

**Comment by cs123951** [comment]
Thank you for your rapid reply! The stitching issue is not from decimation3 network but from my self-designed network. But your answers is a great help to me. Thank you again.
